### PR TITLE
! Fix content type of response of robots.txt

### LINKED ISSUE #2: Incorrect Content Type header
`Content-Type:text/html; charset=utf-8`
Should be
`Content-Type:text/plain; charset=utf-8`

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fix #2

I don't know how to test this with integration test
Please guide me if you need a test case (or add it later yourself :)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
@lassebunk PING!

**Comment by lassebunk** [comment]
Thanks.
I think the `render` method can take a `:content_type` option. Could you try this?
:-]

**Comment by lassebunk** [comment]
Pong! :-)

**Comment by PikachuEXE** [comment]
Tested & pushed!

**Comment by PikachuEXE** [comment]
Ball! :soccer:

**Comment by lassebunk** [comment]
8ball! :8ball: ;-))

Thanks :)

**Comment by PikachuEXE** [comment]
is it possible to have a test case for it?

**Comment by lassebunk** [comment]
Yes, I just did that in https://github.com/lassebunk/human_power/commit/b0571db5c2feeb39c0c4453a4ecc1a4a22c32a01

**Comment by lassebunk** [comment]
:information_source: These changes are now available in 0.0.6

**Comment by PikachuEXE** [comment]
Upgrading now :wink:

**Comment by lassebunk** [comment]
Nice :blush:

**Comment by lassebunk** [comment]
And thanks for helping out :+1:

**Pull request merged**
